[fixed_asset_aeroo_report] 8.0.1.1.0
open-synergy/opnsynid-fixed-asset-aeroo-report pull request #5
Opened 2021-05-12 07:49 UTC by mikevhe18

2021-05-15 03:10 UTC, andhit-r requested changes

2021-05-15 03:10 UTC, andhit-r commented on fixed_asset_aeroo_report/reports/report_fixed_asset.py
> +            sorted = \
Ini nilainya yang diambilnya juga diubah ke field salvage_value

2021-05-15 03:10 UTC, andhit-r commented on fixed_asset_aeroo_report/reports/report_fixed_asset.py
> +                filtered.sorted(key=lambda s: s.id, reverse=True)[0]
Mike klo lo mau pake sorted maka ikuti order asli dr model. Lihat disini https://github.com/open-synergy/opnsynid-fixed-asset/blob/24651f2380f3b1a186660416805fe0e7feef0097/fixed_asset/models/account_asset_depreciation_line.py#L14.

Atau lo ga usah pakai sorted tinggal pakai index [:-1]

2021-05-15 03:10 UTC, andhit-r commented on fixed_asset_aeroo_report/reports/report_fixed_asset.py
> +                filtered.sorted(key=lambda s: s.line_date, reverse=True)[0]
Mike klo lo mau pake sorted maka ikuti order asli dr model. Lihat disini https://github.com/open-synergy/opnsynid-fixed-asset/blob/24651f2380f3b1a186660416805fe0e7feef0097/fixed_asset/models/account_asset_depreciation_line.py#L14.

Atau lo ga usah pakai sorted tinggal pakai index [:-1]

2021-05-17 08:11 UTC, mikevhe18 commented on fixed_asset_aeroo_report/reports/report_fixed_asset.py
> +            sorted = \
@andhit-r mas, di object depreciation_line tidak ada field "**salvage_value**, diambil dari header kah ?

2021-05-18 09:46 UTC, andhit-r requested changes

2021-05-18 09:46 UTC, andhit-r commented on fixed_asset_aeroo_report/reports/report_fixed_asset.py
> +            or x.move_check
Mike ini lo hrs kasih kurung

2021-05-18 09:46 UTC, andhit-r commented on fixed_asset_aeroo_report/reports/report_fixed_asset.py
> +                    key=lambda r: (r.type, r.line_date), reverse=True)[0]
Hati-hati jika len dari filtered == 0. Kode ini pasti error.

2021-05-18 11:00 UTC, mikevhe18 commented on fixed_asset_aeroo_report/reports/report_fixed_asset.py
> +                    key=lambda r: (r.type, r.line_date), reverse=True)[0]
Mas ini kan diatasnya sudah dikasih pengaman "if filtered", jadi pasti ketika di sorted, datanya tidak akan kosong

2021-05-19 10:49 UTC, merged